### ISSUE TITLE
Domain white list not work

### ISSUE THREAD

**Issue by gsmdude** [gfnlabs/link-proxy#2]
![01](https://cloud.githubusercontent.com/assets/11229505/6412829/9b787ba8-beaa-11e4-83eb-32cb5f054932.jpg)

![02](https://cloud.githubusercontent.com/assets/11229505/6412919/bd9147be-beab-11e4-9bd7-de6989821c27.jpg)

i don't know why this not work for me,

**Comment by sikhlana** [comment]
There wasn't any error logged?

This can be an issue with PHP unable to parse the URL as expected.

**Comment by gsmdude** [comment]
i can't see any error, if i add a single domain this working fine. but multiple domain not work, i mean only 1 domain work on white list.

**Comment by sikhlana** [comment]
okay... so it might be an issue with preg_split, go to this file and line: https://github.com/gfnlabs/link-proxy/blob/master/upload/library/GFNLinkProxy/Api.php#L38

change
```
$whiteList = preg_split('/\r?\n/', $whiteList, PREG_SPLIT_NO_EMPTY);
```

to
```
$whiteList = explode("\n", $whiteList);
```

and see what happens :smiley:

**Comment by gsmdude** [comment]
Thanks. now working fine. :smiley:

**Comment by sikhlana** [comment]
Awesome! Gonna push a new update to fix this as others might run into the same issue. :+1:
